# TODO: add dev/prod profile(s)
# TODO: add nginx reverse proxy

services:
  frontend:
    build: ./frontend
    volumes:
      - nextjs-cache:/workspace/.next
      - node-modules:/workspace/node_modules
      - ./frontend:/workspace:cached
    working_dir: /workspace
    command: pnpm run dev
    restart: unless-stopped
    ports:
      - "8000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/workspace:cached
    working_dir: /workspace
    command: invoke run-back-debug #TODO: switch to wsgi for prod
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - "8001:5000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: retroolympics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
  nextjs-cache:
  node-modules:
